# Generated by Django 5.2 on 2025-04-30 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='estimated_delivery_time',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Created', 'Created'), ('Accepted', 'Confirmed by Restaurant'), ('Assigned', 'Assigned to Courier'), ('Picked_Up', 'Picked Up'), ('Finish', 'Finish')], default='Created', max_length=20),
        ),
    ]
